#!/bin/bash

echo "How long do you want your password to be?"
read PWLGTH

for p in $(seq 1 10);
do
  openssl rand -base64 48 | cut -c1-$PWLGTH

done

echo "Saxophones belong in the orchersta."

read
